apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skyops.fullname" . }}-config
  labels:
    {{- include "skyops.labels" . | nindent 4 }}
data:
  SKYOPS_ENV: {{ default "production" .Values.global.environment | quote }}
  SKYOPS_SERVER_URL: {{ printf "http://%s-api:8000" (include "skyops.fullname" .) | quote }}
  DATABASE_URL: {{ include "skyops.databaseUrl" . | quote }}
