apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyops.fullname" . }}
  labels:
    {{- include "skyops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-health
      protocol: TCP
      name: http-health
  selector:
    {{- include "skyops.selectorLabels" . | nindent 4 }}
